### ISSUE TITLE
Uncaught TypeError: Cannot read property 'start' of undefined

### ISSUE THREAD

**Issue by amoeba** [forivall/atom-hard-wrap#1]
Nice package! It's coming in very handy today.

If I try to `hard-wrap:reflow-selection` in an empty paragraph, i.e. where the X is in the following code block:

``` text
...
end of some paragraph.

X

Start of another paragraph...
```

I receive the error `Uncaught TypeError: Cannot read property 'start' of undefined`. I expected nothing to happen.

**Comment by forivall** [comment]
fixed and new release published.

**Comment by amoeba** [comment]
Thanks for the quick fix!
