### ISSUE TITLE
Installs indefinitely

### ISSUE THREAD

**Issue by amf2015** [forivall/atom-hard-wrap#49]
When I attempt to install, it just keeps installing without stopping. It doesn't quit installing or give any error, it just never finishes installing.

**Comment by ttshivers** [comment]
I am encountering the same error

**Comment by lebedov** [comment]
Also encountering the same problem with Atom 1.21.2.

**Comment by forivall** [comment]
I removed the underscore-plus dependency, hopefully that helps.
