### ISSUE TITLE
Not working with non-latin characters

### ISSUE THREAD

**Issue by gaintsev** [forivall/atom-hard-wrap#7]
Hello!
Thanks for your package. However, it seems not working with non-latin characters (I use Cyrillic alphabet).

**Comment by forivall** [comment]
Thanks for the bug report!

Could you test to see if it works in https://github.com/atom/autoflow? Or at least drop a gist with an example file full of cyrillic text (like lorem ipsum with cyrillic or something? Does that exist?)

**Comment by gaintsev** [comment]
Yes, it works with Autoflow.

Here is an example of random Cyrillic text - [gist](https://gist.github.com/gaintsev/59bb55296829878d280acbde157b826f).

Here's a site that generates random text in the Cyrillic alphabet - https://yandex.ru/referats/

**Comment by darklynx** [comment]
I have experienced the same issue, Russian text, in UTF-8 and Windows 1521 encodings, the "Preferred Line Length" is set to 120 chars, but it gets broken at all

**Update:** actually, the latest released version (v1.0.1) that is installed does not even have `hard-wrap.js` file, it has `hard-wrap.coffee` and no support for Cyrillic, it is a way outdated. @gaintsev do you plan to release a current version from master branch?

**Update 2:** I have tested the version from master branch by cloning it directly to `~/.atom/packages` folder and running `npm update`, and I can confirm that the version from **master** branch works well with Cyrillic letters.

**Comment by darklynx** [comment]
I'm not sure, but it could be related to a missing backslash here (in Cyrillic line):
```
...
const CHARACTER_RE = new RegExp(`\
[\
\\w${/* English */''}\
\u0410-\u042F\u0401\u0430-\u044F\u0451${/* Cyrillic */''}\
]\
`)
...
```

`\u0410` - is a unicode char, but in case of English the expression is started with leading `\`

**Comment by forivall** [comment]
Huh, I fixed it in January, but never published a new version. I did that just now.

**Comment by darklynx** [comment]
great! it works now

**Comment by gaintsev** [comment]
Yes, now it works, thanks!
